#!/usr/bin/env bash
set -euo pipefail

out_file=${1:-../out/report.txt}
{
  printf 'Pipeworks report\n'
  printf 'Generated by: %s\n' "${USER:-unknown}"
  printf 'Current directory: %s\n' "$(pwd)"
} > "$out_file"
